// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// ITrade is an autogenerated mock type for the ITrade type
type ITrade struct {
	mock.Mock
}

// GetListTradeByYears provides a mock function with given fields: c
func (_m *ITrade) GetListTradeByYears(c *gin.Context) {
	_m.Called(c)
}

// UpsertTradeData provides a mock function with given fields: c
func (_m *ITrade) UpsertTradeData(c *gin.Context) {
	_m.Called(c)
}

// NewITrade creates a new instance of ITrade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITrade(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITrade {
	mock := &ITrade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
