// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "VincentLimarus/stock-analyzer-performance/model"
)

// IHealth is an autogenerated mock type for the IHealth type
type IHealth struct {
	mock.Mock
}

// Check provides a mock function with given fields: ctx
func (_m *IHealth) Check(ctx context.Context) (model.HTTPResponse, bool) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 model.HTTPResponse
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context) (model.HTTPResponse, bool)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) model.HTTPResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(model.HTTPResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// NewIHealth creates a new instance of IHealth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIHealth(t interface {
	mock.TestingT
	Cleanup(func())
}) *IHealth {
	mock := &IHealth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
