// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IRegistry is an autogenerated mock type for the IRegistry type
type IRegistry struct {
	mock.Mock
}

// NewIRegistry creates a new instance of IRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRegistry {
	mock := &IRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
