// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IServer is an autogenerated mock type for the IServer type
type IServer struct {
	mock.Mock
}

// Serve provides a mock function with given fields: ctx
func (_m *IServer) Serve(ctx context.Context) {
	_m.Called(ctx)
}

// NewIServer creates a new instance of IServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *IServer {
	mock := &IServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
