// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	health "VincentLimarus/stock-analyzer-performance/service/health"

	mock "github.com/stretchr/testify/mock"

	trades "VincentLimarus/stock-analyzer-performance/service/trades"
)

// IRegistry is an autogenerated mock type for the IRegistry type
type IRegistry struct {
	mock.Mock
}

// GetHealth provides a mock function with no fields
func (_m *IRegistry) GetHealth() health.IHealth {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHealth")
	}

	var r0 health.IHealth
	if rf, ok := ret.Get(0).(func() health.IHealth); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(health.IHealth)
		}
	}

	return r0
}

// GetTrade provides a mock function with no fields
func (_m *IRegistry) GetTrade() trades.ITrade {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTrade")
	}

	var r0 trades.ITrade
	if rf, ok := ret.Get(0).(func() trades.ITrade); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(trades.ITrade)
		}
	}

	return r0
}

// NewIRegistry creates a new instance of IRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRegistry {
	mock := &IRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
