// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	repository "VincentLimarus/stock-analyzer-performance/repository"

	mock "github.com/stretchr/testify/mock"
)

// TxOpt is an autogenerated mock type for the TxOpt type
type TxOpt struct {
	mock.Mock
}

// Execute provides a mock function with given fields: t
func (_m *TxOpt) Execute(t *repository.TransactionRunner) {
	_m.Called(t)
}

// NewTxOpt creates a new instance of TxOpt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxOpt(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxOpt {
	mock := &TxOpt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
