// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	dto "VincentLimarus/stock-analyzer-performance/model/dto/http/trades"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ITrade is an autogenerated mock type for the ITrade type
type ITrade struct {
	mock.Mock
}

// GetListTradeByYears provides a mock function with given fields: ctx, years
func (_m *ITrade) GetListTradeByYears(ctx context.Context, years []string) ([]dto.TradeData, error) {
	ret := _m.Called(ctx, years)

	if len(ret) == 0 {
		panic("no return value specified for GetListTradeByYears")
	}

	var r0 []dto.TradeData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]dto.TradeData, error)); ok {
		return rf(ctx, years)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []dto.TradeData); ok {
		r0 = rf(ctx, years)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.TradeData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, years)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertTradeData provides a mock function with given fields: ctx, payload
func (_m *ITrade) UpsertTradeData(ctx context.Context, payload []dto.TradeData) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for UpsertTradeData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []dto.TradeData) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewITrade creates a new instance of ITrade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITrade(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITrade {
	mock := &ITrade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
